### ISSUE TITLE
SAVE PATH??

### ISSUE THREAD

**Issue by HassanDev13** [petehouston/learn-dart#1]
i try this method downloadBinaryFile() 
he give this error 

E/flutter (29007): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot open file, path = './logo.png' (OS Error: Read-only file system, errno = 30)

**Comment by petehouston** [comment]
Hmmm, are you trying to download files in Flutter? Do you mind showing your code and location of the `logo.png` in project structure?

**Comment by HassanDev13** [comment]
import 'package:flutter/material.dart';
import 'dart:io';
import 'dart:convert';

void main() => runApp(MaterialApp(home:MyApp()));

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Scaffold(appBar: AppBar(),
      body: Center(
        child: Center(child:  RaisedButton(
          onPressed: () {
            downloadBinaryFile();
          },
          color: Colors.white,
          child: const Text(
            'Run',
            style: TextStyle(fontSize: 20,color: Colors.red)
          ),
        ),),
      ),

    );
  }
  void downloadBinaryFile() {
  HttpClient client = new HttpClient();
  var _downloadData = List<int>();
  var fileSave = new File('./logo.png');
  client.getUrl(Uri.parse("https://fluttermaster.com/wp-content/uploads/2018/08/fluttermaster.com-logo-web-header.png"))
      .then((HttpClientRequest request) {
    return request.close();
  })
      .then((HttpClientResponse response) {
    response.listen((d) => _downloadData.addAll(d),
        onDone: () {
          fileSave.writeAsBytes(_downloadData);
        }
    );
  });
}




}

**Comment by HassanDev13** [comment]
i want to download pdf fils when user click a button do u think this code work's fin for me or do u have any suggestion ?

**Comment by HassanDev13** [comment]
Any solution please?

**Comment by petehouston** [comment]
You should use `path_provider` to query the app document directory or cache directory, and save files into those directories.

Update the dependencies:

```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.0
```

Usage like below:

```dart
import 'package:path_provider/path_provider.dart';

void downloadFile() async {
  HttpClient client = new HttpClient();
  var request = await client.getUrl(Uri.parse("https://fluttermaster.com/wp-content/uploads/2018/08/fluttermaster.com-logo-web-header.png"));
  var response = await request.close();

  Directory appDocDir = await getApplicationDocumentsDirectory();
  String appDocPath = appDocDir.path;
  print(appDocPath); // see logs to verify final path
  return response.pipe(new File('$appDocPath/logo.png').openWrite());
}
```
